Eliminate hardcoded values + move them at the beginning of file
banzaicloud/koperator pull request #1043
Opened 2023-08-17 05:59 UTC by szykes

## Description

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.

Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

## Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](../CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-08-17 05:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/koperator?pullRequest=1043) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/koperator?pullRequest=1043) before we can accept your contribution.<br/><hr/>**szykes** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/koperator?pullRequest=1043) it.</sub>

2023-08-18 18:27 UTC, panyuenlau reviewed
Question: is it intentional to remove the comments for the existing const variables? If so, why?

2023-08-21 11:25 UTC, szykes commented
> Question: is it intentional to remove the comments for the existing const variables? If so, why?

It was intentional. I think the comments were information duplications.

`// DefaultKafkaImage is the default Kafka image used when users don't specify it in KafkaClusterSpec.ClusterImage
DefaultKafkaImage = "ghcr.io/banzaicloud/kafka:2.13-3.4.1"`

vs

`// Kafka Cluster Spec
...
defaultKafkaImage = "ghcr.io/banzaicloud/kafka:2.13-3.4.1"`

2023-08-21 13:10 UTC, panyuenlau commented
> I think the comments were information duplications.

I don't necessary agree this is true for all the const vars..., for example:
```golang
	// DefaultAnyCastPort kafka anycast port that can be used by clients for metadata queries
	DefaultAnyCastPort = 29092
	// DefaultIngressControllerTargetPort is the default container port for the ingress controller
	DefaultIngressControllerTargetPort = 29092
```
without the comments, I don't think these two vars are straightforward enough for others to understand what they are used for (assuming without looking into the implementation).

2023-08-22 09:41 UTC, szykes commented
The commenting thing is not an easy topic.

I have kept the first code comment of your comment. In addition, I have added the "chart path" for most of the defaults.

2023-08-22 13:28 UTC, panyuenlau requested changes
Comment 1 (possibly a nit): I think using block comments would create better visual separations between the different configuration sections. 

Comment 2: plz split this PR into two - one for the changes under the `api` module, and one for the rest of the changes because the refactoring in `pkg/resources/kafka/pod.go` requires a new api tag

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// General
```suggestion
	/* General Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// Envoy Config
```suggestion
	/* Envoy Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// External Listener Config
```suggestion
	/* External Listener Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// Broker Config
```suggestion
	/* Broker Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// Cruise Control Config
```suggestion
	/* Cruise Control Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// Istio Ingress Config
```suggestion
	/* Istio Ingress Config */
```

2023-08-22 13:28 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// Monitor Config
```suggestion
	/* Monitor Config */
```

2023-08-24 07:16 UTC, szykes reviewed
Use different comment type to separate blocks of const

2023-08-24 13:01 UTC, panyuenlau approved these changes
LGTM, thanks for the work!

2023-08-24 13:09 UTC, Kuvesz approved these changes
lgtm

2023-08-25 09:14 UTC, merged