Pass DNS fields to the CSR if specified in the KafkaUserSpec
banzaicloud/koperator pull request #721
Opened 2021-12-13 13:53 UTC by adamantal

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | - |
| License         | Apache 2.0 |

### What's in this PR?

A simple PR to pass DNS fields in the CSR if specified in the `KafkaUserSpec`.

### Why?

Otherwise the PKI manager would create a certificate that does not contain the DNS names as SAN.

### Checklist

- [ ] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

2021-12-13 14:07 UTC, stoader requested changes
Can we add a unit test which verifies that the CSR is created with the correct content?

2021-12-14 11:10 UTC, adamantal commented
Tested manually and verified that the generated cert contains the string in its SAN field.

2021-12-14 11:39 UTC, hi-im-aren reviewed
I wonder if gomega based assertions would be beneficial even if we skip ginkgo. It's already used in various parts of the project, might as well decide sooner or later which route we are taking.

2021-12-14 11:39 UTC, hi-im-aren commented on pkg/pki/k8scsrpki/k8scsr_test.go
> +	return cluster
```suggestion
	return &v1beta1.KafkaCluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "test",
			Namespace: "test-namespace",
		},
		Spec: v1beta1.KafkaClusterSpec{
			ListenersConfig: v1beta1.ListenersConfig{
				InternalListeners: []v1beta1.InternalListenerConfig{
					{
						CommonListenerSpec: v1beta1.CommonListenerSpec{
							ContainerPort: 9092,
						},
					},
				},
				SSLSecrets: &v1beta1.SSLSecrets{
					PKIBackend: v1beta1.PKIBackendK8sCSR,
				},
			},
		},
	}
```

2021-12-14 13:04 UTC, adamantal commented
> I wonder if gomega based assertions would be beneficial even if we skip ginkgo. It's already used in various parts of the project, might as well decide sooner or later which route we are taking instead of mix matching.

The tests use gomega now.

2021-12-14 13:06 UTC, hi-im-aren approved these changes

2021-12-14 13:07 UTC, stoader approved these changes

2021-12-14 13:13 UTC, merged