Fix broker pods doesn't restarting beause no healthy brokers present
banzaicloud/koperator pull request #802
Opened 2022-04-27 14:12 UTC by bartam1

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

### What's in this PR?
 If reconcilePerBrokerDynamicConfig gets an error then I let the loop continue to the next broker. A combined error will be returned after the broker loop so the operator will try again later. 

### Why?
When in a kafka cluster there is not any working kafka broker present, but there are multiple broker pods with terminated container, only one broker pod will be restarted. Other brokers with terminated containers will not until  at least one healthy broker will be present in the kafka cluster. Brokers are unreachable and reconcilePerBrokerDynamicConfig function run in error.

### Checklist
- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x] Logging code meets the guideline

2022-04-27 14:14 UTC, Kuvesz approved these changes
LGTM

2022-04-27 14:47 UTC, hi-im-aren commented on pkg/resources/kafka/kafka.go
> +			perBrokerDynamicConfigCombineError = errors.Combine(perBrokerDynamicConfigCombineError, err)
We could add some details for the error like `broker.Id, brokerConfig, configMap`

2022-04-29 08:43 UTC, pregnor submitted a review, later dismissed
LGTM

2022-04-29 08:45 UTC, Kuvesz submitted a review, later dismissed

2022-05-02 06:38 UTC, stoader requested changes

2022-05-02 06:38 UTC, stoader commented on pkg/resources/kafka/kafka.go
> +		return errors.New("setting dynamic configs for some brokers has failed.")
Add context to the error (e.g. see https://github.com/banzaicloud/koperator/blob/master/pkg/resources/kafka/kafka.go#L304-L307)

2022-05-02 06:38 UTC, stoader commented on pkg/resources/kafka/kafka.go
> +	isPerBrokerDynamicConfigFailed := false
How about `allBrokerDynamicConfigSucceeded := true` and than if an error occurs set it to `false`

2022-05-02 22:59 UTC, pregnor submitted a review, later dismissed

2022-05-03 05:08 UTC, stoader submitted a review, later dismissed

2022-05-04 11:11 UTC, pregnor approved these changes

2022-05-04 11:11 UTC, bartam1 commented
I have disabled the cyclo check for the reconcile function temporarily.
Im going to make refactor for the reconcile function and put back cyclo check in another PR

2022-05-04 11:24 UTC, stoader approved these changes

2022-05-05 08:40 UTC, merged