Upgrade dependencies
banzaicloud/koperator pull request #831
Opened 2022-07-12 15:57 UTC by amuraru

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| License         | Apache 2.0 |

### What's in this PR?

Upgrade dependencies

### Why?
Keeping them up to date.

### Additional context

### Checklist

- [x] Implementation tested
- [x] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)

2022-07-12 19:05 UTC, pregnor requested changes

2022-07-12 19:13 UTC, amuraru commented on api/go.mod
> +	github.com/imdario/mergo v0.3.13
My understanding is that the migration to v1 certmanager APIs was already done in https://github.com/banzaicloud/koperator/commit/9ed415396149bcb12f87166e070361ab57f49f7f

2022-07-12 20:26 UTC, stoader approved these changes
I think references to cert manager needs to be updated in kafka docs to point to the new version: https://github.com/banzaicloud/koperator-docs

2022-07-12 20:28 UTC, stoader commented on api/go.mod
> +	github.com/imdario/mergo v0.3.13
yes the migration to `v1` was already done

2022-07-13 09:01 UTC, pregnor commented on api/go.mod
> +	github.com/imdario/mergo v0.3.13
I found a couple references to the removed cert-manager `apiVersion`s: https://github.com/banzaicloud/koperator/search?q=v1alpha2

2022-07-13 09:05 UTC, stoader commented on api/go.mod
> +	github.com/imdario/mergo v0.3.13
those are used when koperator is deployed using `make deploy` which relies on kustomize. Let's fix those in a separate PR

2022-07-13 09:05 UTC, pregnor approved these changes

2022-07-13 13:35 UTC, merged