Fix documentation for ClientSSLCertSecret and ServerSSLCertSecret
banzaicloud/koperator pull request #840
Opened 2022-07-28 09:41 UTC by bartam1

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #839  |
| License         | Apache 2.0 |

### What's in this PR?
It fixes the documentation for the ClientSSLCertSecret and ServerSSLCertSecret.

### Why?
The secret which is referenced by the ClientSSLCertSecret and ServerSSLCertSecret needs to contain other fields than the keystore.jks, truststore.jks and password for proper work

2022-07-28 09:50 UTC, panyuenlau submitted a review, later dismissed
Not sure if these are the better way of rephrasing them

2022-07-28 09:50 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// the tls certificate, tls private key, CA certificate in PEM and base64 encoded format
```suggestion
	// the tls certificate, tls private key, CA certificate in PEM format with base64 encoding
```

2022-07-28 09:50 UTC, panyuenlau commented on api/v1beta1/kafkacluster_types.go
> +	// The secret must contain the keystore, truststore jks files and the password for them in base64 encoded format and the tls certificate in PEM and base64 encoded format
```suggestion
	// The secret must contain the keystore, truststore jks files and the password for them in base64 encoded format and the tls certificate in PEM format with base64 encoding
```

2022-07-28 09:51 UTC, pregnor approved these changes
LGTM aside from Darren's comments

2022-07-28 09:55 UTC, stoader requested changes
Run `make manifests` to ensure that all artifacts are updated

2022-07-29 12:18 UTC, pregnor approved these changes
LGTM

2022-07-29 12:19 UTC, stoader approved these changes

2022-07-29 12:40 UTC, panyuenlau approved these changes

2022-08-02 08:49 UTC, panyuenlau commented
@bartam1 Can we merge this?

2022-08-02 08:59 UTC, merged