Move workflows to github actions
banzaicloud/koperator pull request #860
Opened 2022-09-02 13:00 UTC by asdwsda

Move workflows to github actions

2022-09-06 09:07 UTC, pregnor requested changes
Aside from the comment, looks good.

2022-09-06 09:44 UTC, pregnor approved these changes

2022-09-06 10:51 UTC, pregnor approved these changes

2022-09-07 10:35 UTC, pregnor commented
Ping

2022-09-07 10:59 UTC, hi-im-aren approved these changes

2022-09-07 11:02 UTC, merged