Use node IP in advertised.listeners
banzaicloud/koperator pull request #901
Opened 2022-11-30 15:35 UTC by balassai

| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no|
| New feature?    | yes |
| API breaks?     | no|
| Deprecations?   | no|
| Related tickets | fixes #900  |
| License         | Apache 2.0 |

### What's in this PR?
Use node IP in advertised.listeners when hostnameOverride and nodePortExternalIP are not set

### Additional context
When "hostNameOverride" and brokerConfig.nodePortExternalIP are empty and NodePort access method is selected the NodePortNodeAdddressType defines the external listener Address that shall be used in the advertised.listeners property. 
If NodePortNodeAddressType is not provided the first non empty address is used in the following order:
1. ExternalIP
2. InternalIP

### Checklist

- [ x] Implementation tested
- [x ] Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)
- [x ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)

2022-12-05 17:14 UTC, bartam1 requested changes

2022-12-05 17:22 UTC, bartam1 commented
Thank you for your effort to do this!

2022-12-05 21:38 UTC, bartam1 commented on pkg/resources/kafka/kafka.go
> +func (r *Reconciler) getK8sAssignedNode(log logr.Logger, brokerId int32, nodeAddressType string) (string, error) {
We can use more descriptive function name like: getK8sAssignedNodeAddress

2022-12-06 09:53 UTC, pregnor reviewed
Aside from Márton's comments I didn't find anything else.
Thanks for the contribution.

2022-12-06 09:53 UTC, pregnor commented on api/v1beta1/kafkacluster_types.go
> +	// 2. InternalIP
In that case please also update the describing comment accordingly.

2023-01-09 16:43 UTC, panyuenlau commented
Hey @balassai, since this PR has been opened for a while, can you provide some updates on this?

2023-02-21 07:58 UTC, Jcodelove commented
A very useful function. I hope to see it on the main branch immediately！！

2023-02-21 09:00 UTC, bartam1 commented
Im going to fix this PR and we can merge it.

2023-02-21 10:46 UTC, closed without merging

2023-03-01 12:34 UTC, bartam1 commented
Merged into the master
cc @Jcodelove